### ISSUE TITLE
Install on Mac?

### ISSUE THREAD

**Issue by RichN001** [TUVIMEN/hgrep#2]
this should build on MacOS yeah? or only linux

` make install      
src/main.c src/flexarr.c src/hgrep.c src/ctype.c
hgrep build options:
CFLAGS   = -O3 -march=native -Wall -Wextra -DVERSION="1.7" -DPHPTAGS -DAUTOCLOSING
LDFLAGS  = 
CC       = gcc -std=c99
gcc -std=c99 -O3 -march=native -Wall -Wextra -DVERSION=\"1.7\" -DPHPTAGS -DAUTOCLOSING -c src/main.c -o src/main.o
sr**c/main.c:32:10: fatal error: 'linux/limits.h' file not found**
#include <linux/limits.h>`

**Comment by TUVIMEN** [comment]
I think it has been fixed by this [commit](https://github.com/TUVIMEN/hgrep/commit/a3b9a3a0db43aa08bd5879867d51ff9a213b0009).

Sorry, but i didn't notice this issue up until yesterday.
